# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'untitled.ui'
##
## Created by: Qt User Interface Compiler version 6.1.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import *  # type: ignore
from PySide6.QtGui import *  # type: ignore
from PySide6.QtWidgets import *  # type: ignore
from PySide6 import QtWidgets
from gui_help import Ui_help_window


class Ui_main_window(object):
    
    # Metoda pro zobrazení modálního okna nápovědy
    def show_help(self):
        self.help_window = QtWidgets.QMainWindow()
        self.gui_help = Ui_help_window()
        self.gui_help.setupUi(self.help_window)
        self.help_window.show()

    def setupUi(self, main_window):
        if not main_window.objectName():
            main_window.setObjectName(u"main_window")
        main_window.resize(1101, 552)
        icon = QIcon()
        icon.addFile(u"img/icon.png", QSize(), QIcon.Normal, QIcon.Off)
        main_window.setWindowIcon(icon)
        self.action_restart = QAction(main_window)
        self.action_restart.setObjectName(u"action_restart")
        icon1 = QIcon()
        icon1.addFile(u"img/restart.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_restart.setIcon(icon1)
        self.action_about = QAction(main_window)
        self.action_about.setObjectName(u"action_about")
        icon2 = QIcon()
        icon2.addFile(u"img/icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_about.setIcon(icon2)
        self.action_help = QAction(main_window)
        self.action_help.setObjectName(u"action_help")
        self.action_help.triggered.connect(self.show_help)
        icon3 = QIcon()
        icon3.addFile(u"img/help.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_help.setIcon(icon3)
        self.central_widget = QWidget(main_window)
        self.central_widget.setObjectName(u"central_widget")
        self.widget_players = QWidget(self.central_widget)
        self.widget_players.setObjectName(u"widget_players")
        self.widget_players.setGeometry(QRect(30, 20, 278, 441))
        self.verticalLayout = QVBoxLayout(self.widget_players)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.label_players = QLabel(self.widget_players)
        self.label_players.setObjectName(u"label_players")
        self.label_players.setMinimumSize(QSize(12, 12))
        font = QFont()
        font.setBold(True)
        self.label_players.setFont(font)

        self.verticalLayout.addWidget(self.label_players)

        self.list_players = QListWidget(self.widget_players)
        self.list_players.setObjectName(u"list_players")
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_players.sizePolicy().hasHeightForWidth())
        self.list_players.setSizePolicy(sizePolicy)
        self.list_players.setMinimumSize(QSize(0, 200))
        self.list_players.setBaseSize(QSize(0, 200))
        self.list_players.viewport().setProperty("cursor", QCursor(Qt.ArrowCursor))
        self.list_players.setSortingEnabled(True)

        self.verticalLayout.addWidget(self.list_players)

        self.button_add = QPushButton(self.widget_players)
        self.button_add.setObjectName(u"button_add")
        self.button_add.setBaseSize(QSize(7, 0))
        self.button_add.setCursor(QCursor(Qt.PointingHandCursor))

        self.verticalLayout.addWidget(self.button_add)

        self.widget_match = QWidget(self.central_widget)
        self.widget_match.setObjectName(u"widget_match")
        self.widget_match.setGeometry(QRect(760, 20, 291, 441))
        self.label_match = QLabel(self.widget_match)
        self.label_match.setObjectName(u"label_match")
        self.label_match.setGeometry(QRect(20, 11, 38, 16))
        self.label_match.setFont(font)
        self.progress_bar = QProgressBar(self.widget_match)
        self.progress_bar.setObjectName(u"progress_bar")
        self.progress_bar.setGeometry(QRect(20, 140, 261, 20))
        self.progress_bar.setMaximum(90)
        self.progress_bar.setValue(0)
        self.progress_bar.setInvertedAppearance(False)
        self.progress_bar.setTextDirection(QProgressBar.TopToBottom)
        self.list_team2_players = QListWidget(self.widget_match)
        self.list_team2_players.setObjectName(u"list_team2_players")
        self.list_team2_players.setGeometry(QRect(20, 210, 256, 211))
        self.widget_my_team = QWidget(self.central_widget)
        self.widget_my_team.setObjectName(u"widget_my_team")
        self.widget_my_team.setGeometry(QRect(330, 21, 411, 441))
        self.radio_rd = QRadioButton(self.widget_my_team)
        self.radio_rd.setObjectName(u"radio_rd")
        self.radio_rd.setGeometry(QRect(270, 280, 108, 20))
        self.radio_rd.setCursor(QCursor(Qt.PointingHandCursor))
        self.radio_rd.setLayoutDirection(Qt.LeftToRight)
        self.radio_gk = QRadioButton(self.widget_my_team)
        self.radio_gk.setObjectName(u"radio_gk")
        self.radio_gk.setGeometry(QRect(160, 410, 81, 20))
        self.radio_gk.setCursor(QCursor(Qt.PointingHandCursor))
        self.radio_gk.setLayoutDirection(Qt.LeftToRight)
        self.label_left_defender = QLabel(self.widget_my_team)
        self.label_left_defender.setObjectName(u"label_left_defender")
        self.label_left_defender.setGeometry(QRect(20, 260, 101, 20))
        sizePolicy1 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.label_left_defender.sizePolicy().hasHeightForWidth())
        self.label_left_defender.setSizePolicy(sizePolicy1)
        self.label_left_defender.setAlignment(Qt.AlignCenter)
        self.label_goalkeeper = QLabel(self.widget_my_team)
        self.label_goalkeeper.setObjectName(u"label_goalkeeper")
        self.label_goalkeeper.setGeometry(QRect(150, 390, 101, 20))
        sizePolicy1.setHeightForWidth(self.label_goalkeeper.sizePolicy().hasHeightForWidth())
        self.label_goalkeeper.setSizePolicy(sizePolicy1)
        self.label_goalkeeper.setAlignment(Qt.AlignCenter)
        self.label_left_striker = QLabel(self.widget_my_team)
        self.label_left_striker.setObjectName(u"label_left_striker")
        self.label_left_striker.setGeometry(QRect(20, 130, 101, 20))
        sizePolicy1.setHeightForWidth(self.label_left_striker.sizePolicy().hasHeightForWidth())
        self.label_left_striker.setSizePolicy(sizePolicy1)
        self.label_left_striker.setAlignment(Qt.AlignCenter)
        self.radio_rs = QRadioButton(self.widget_my_team)
        self.radio_rs.setObjectName(u"radio_rs")
        self.radio_rs.setGeometry(QRect(270, 150, 102, 20))
        self.radio_rs.setCursor(QCursor(Qt.PointingHandCursor))
        self.radio_rs.setLayoutDirection(Qt.LeftToRight)
        self.label_right_striker = QLabel(self.widget_my_team)
        self.label_right_striker.setObjectName(u"label_right_striker")
        self.label_right_striker.setGeometry(QRect(270, 130, 121, 20))
        sizePolicy1.setHeightForWidth(self.label_right_striker.sizePolicy().hasHeightForWidth())
        self.label_right_striker.setSizePolicy(sizePolicy1)
        self.label_right_striker.setAlignment(Qt.AlignCenter)
        self.radio_ls = QRadioButton(self.widget_my_team)
        self.radio_ls.setObjectName(u"radio_ls")
        self.radio_ls.setGeometry(QRect(20, 150, 96, 20))
        self.radio_ls.setCursor(QCursor(Qt.PointingHandCursor))
        self.radio_ls.setLayoutDirection(Qt.LeftToRight)
        self.radio_ld = QRadioButton(self.widget_my_team)
        self.radio_ld.setObjectName(u"radio_ld")
        self.radio_ld.setGeometry(QRect(20, 280, 102, 20))
        self.radio_ld.setCursor(QCursor(Qt.PointingHandCursor))
        self.radio_ld.setLayoutDirection(Qt.LeftToRight)
        self.label_right_defender = QLabel(self.widget_my_team)
        self.label_right_defender.setObjectName(u"label_right_defender")
        self.label_right_defender.setGeometry(QRect(270, 260, 121, 20))
        sizePolicy1.setHeightForWidth(self.label_right_defender.sizePolicy().hasHeightForWidth())
        self.label_right_defender.setSizePolicy(sizePolicy1)
        self.label_right_defender.setAlignment(Qt.AlignCenter)
        self.label_my_team = QLabel(self.widget_my_team)
        self.label_my_team.setObjectName(u"label_my_team")
        self.label_my_team.setGeometry(QRect(11, 11, 52, 16))
        self.label_my_team.setFont(font)
        self.label_ld_img = QLabel(self.widget_my_team)
        self.label_ld_img.setObjectName(u"label_ld_img")
        self.label_ld_img.setGeometry(QRect(40, 200, 61, 61))
        sizePolicy2 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy2.setHorizontalStretch(45)
        sizePolicy2.setVerticalStretch(43)
        sizePolicy2.setHeightForWidth(self.label_ld_img.sizePolicy().hasHeightForWidth())
        self.label_ld_img.setSizePolicy(sizePolicy2)
        self.label_ld_img.setBaseSize(QSize(60, 37))
        self.label_ld_img.setPixmap(QPixmap(u"img/dress.png"))
        self.label_ld_img.setScaledContents(True)
        self.label_rd_img = QLabel(self.widget_my_team)
        self.label_rd_img.setObjectName(u"label_rd_img")
        self.label_rd_img.setGeometry(QRect(300, 200, 61, 61))
        sizePolicy2.setHeightForWidth(self.label_rd_img.sizePolicy().hasHeightForWidth())
        self.label_rd_img.setSizePolicy(sizePolicy2)
        self.label_rd_img.setBaseSize(QSize(60, 37))
        self.label_rd_img.setPixmap(QPixmap(u"img/dress.png"))
        self.label_rd_img.setScaledContents(True)
        self.label_gk_img = QLabel(self.widget_my_team)
        self.label_gk_img.setObjectName(u"label_gk_img")
        self.label_gk_img.setGeometry(QRect(170, 330, 61, 61))
        sizePolicy2.setHeightForWidth(self.label_gk_img.sizePolicy().hasHeightForWidth())
        self.label_gk_img.setSizePolicy(sizePolicy2)
        self.label_gk_img.setBaseSize(QSize(60, 37))
        self.label_gk_img.setPixmap(QPixmap(u"img/dress.png"))
        self.label_gk_img.setScaledContents(True)
        self.label_ls_img = QLabel(self.widget_my_team)
        self.label_ls_img.setObjectName(u"label_ls_img")
        self.label_ls_img.setGeometry(QRect(40, 60, 61, 61))
        sizePolicy2.setHeightForWidth(self.label_ls_img.sizePolicy().hasHeightForWidth())
        self.label_ls_img.setSizePolicy(sizePolicy2)
        self.label_ls_img.setBaseSize(QSize(60, 37))
        self.label_ls_img.setPixmap(QPixmap(u"img/dress.png"))
        self.label_ls_img.setScaledContents(True)
        self.label_rs_img = QLabel(self.widget_my_team)
        self.label_rs_img.setObjectName(u"label_rs_img")
        self.label_rs_img.setGeometry(QRect(300, 60, 61, 61))
        sizePolicy2.setHeightForWidth(self.label_rs_img.sizePolicy().hasHeightForWidth())
        self.label_rs_img.setSizePolicy(sizePolicy2)
        self.label_rs_img.setBaseSize(QSize(60, 37))
        self.label_rs_img.setPixmap(QPixmap(u"img/dress.png"))
        self.label_rs_img.setScaledContents(True)
        self.layoutWidget = QWidget(self.widget_my_team)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(120, 10, 280, 30))
        self.grid_team1_name = QGridLayout(self.layoutWidget)
        self.grid_team1_name.setObjectName(u"grid_team1_name")
        self.grid_team1_name.setContentsMargins(0, 0, 0, 0)
        self.label = QLabel(self.layoutWidget)
        self.label.setObjectName(u"label")
        self.label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.grid_team1_name.addWidget(self.label, 0, 0, 1, 1)

        self.team1_name = QLineEdit(self.layoutWidget)
        self.team1_name.setObjectName(u"team1_name")

        self.grid_team1_name.addWidget(self.team1_name, 0, 1, 1, 1)

        self.button_change_name = QPushButton(self.layoutWidget)
        self.button_change_name.setObjectName(u"button_change_name")
        self.button_change_name.setCursor(QCursor(Qt.PointingHandCursor))

        self.grid_team1_name.addWidget(self.button_change_name, 0, 2, 1, 1)

        self.layoutWidget1 = QWidget(self.central_widget)
        self.layoutWidget1.setObjectName(u"layoutWidget1")
        self.layoutWidget1.setGeometry(QRect(780, 52, 256, 67))
        self.grid_match_info = QGridLayout(self.layoutWidget1)
        self.grid_match_info.setObjectName(u"grid_match_info")
        self.grid_match_info.setContentsMargins(0, 0, 0, 0)
        self.label_team2_name = QLabel(self.layoutWidget1)
        self.label_team2_name.setObjectName(u"label_team2_name")
        self.label_team2_name.setAlignment(Qt.AlignCenter)

        self.grid_match_info.addWidget(self.label_team2_name, 0, 1, 1, 1)

        self.label_16 = QLabel(self.layoutWidget1)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.grid_match_info.addWidget(self.label_16, 1, 0, 1, 1)

        self.label_14 = QLabel(self.layoutWidget1)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.grid_match_info.addWidget(self.label_14, 0, 0, 1, 1)

        self.button_set_team2 = QPushButton(self.layoutWidget1)
        self.button_set_team2.setObjectName(u"button_set_team2")
        self.button_set_team2.setCursor(QCursor(Qt.PointingHandCursor))

        self.grid_match_info.addWidget(self.button_set_team2, 0, 2, 1, 1)

        self.label_score = QLabel(self.layoutWidget1)
        self.label_score.setObjectName(u"label_score")
        self.label_score.setAlignment(Qt.AlignCenter)
        self.label_score.setMargin(7)

        self.grid_match_info.addWidget(self.label_score, 1, 1, 1, 1)

        self.button_play = QPushButton(self.layoutWidget1)
        self.button_play.setObjectName(u"button_play")
        self.button_play.setCursor(QCursor(Qt.PointingHandCursor))

        self.grid_match_info.addWidget(self.button_play, 1, 2, 1, 1)

        self.label_opponent_team = QLabel(self.central_widget)
        self.label_opponent_team.setObjectName(u"label_opponent_team")
        self.label_opponent_team.setGeometry(QRect(780, 210, 256, 16))
        self.label_opponent_team.setFont(font)
        self.label_progress_bar = QLabel(self.central_widget)
        self.label_progress_bar.setObjectName(u"label_progress_bar")
        self.label_progress_bar.setGeometry(QRect(780, 140, 256, 16))
        self.label_progress_bar.setFont(font)
        main_window.setCentralWidget(self.central_widget)
        self.menu_bar = QMenuBar(main_window)
        self.menu_bar.setObjectName(u"menu_bar")
        self.menu_bar.setGeometry(QRect(0, 0, 1101, 26))
        self.menu_main = QMenu(self.menu_bar)
        self.menu_main.setObjectName(u"menu_main")
        main_window.setMenuBar(self.menu_bar)
        self.statusbar = QStatusBar(main_window)
        self.statusbar.setObjectName(u"statusbar")
        main_window.setStatusBar(self.statusbar)

        self.menu_bar.addAction(self.menu_main.menuAction())
        self.menu_main.addAction(self.action_restart)
        self.menu_main.addAction(self.action_help)
        self.menu_main.addSeparator()
        self.menu_main.addAction(self.action_about)

        self.retranslateUi(main_window)

        QMetaObject.connectSlotsByName(main_window)
    # setupUi

    def retranslateUi(self, main_window):
        main_window.setWindowTitle(QCoreApplication.translate("main_window", u"Football Manager by lukazko", None))
        self.action_restart.setText(QCoreApplication.translate("main_window", u"Restart", None))
        self.action_about.setText(QCoreApplication.translate("main_window", u"About", None))
        self.action_help.setText(QCoreApplication.translate("main_window", u"Help", None))
        self.label_players.setText(QCoreApplication.translate("main_window", u"Hr\u00e1\u010di", None))
        self.button_add.setText(QCoreApplication.translate("main_window", u"P\u0159idat do t\u00fdmu", None))
        self.label_match.setText(QCoreApplication.translate("main_window", u"Z\u00e1pas", None))
        self.progress_bar.setFormat(QCoreApplication.translate("main_window", u"%v min", None))
        self.radio_rd.setText(QCoreApplication.translate("main_window", u"Prav\u00fd obr\u00e1nce", None))
        self.radio_gk.setText(QCoreApplication.translate("main_window", u"Brank\u00e1\u0159", None))
        self.label_left_defender.setText(QCoreApplication.translate("main_window", u"-", None))
        self.label_goalkeeper.setText(QCoreApplication.translate("main_window", u"-", None))
        self.label_left_striker.setText(QCoreApplication.translate("main_window", u"-", None))
        self.radio_rs.setText(QCoreApplication.translate("main_window", u"Prav\u00fd \u00fato\u010dn\u00edk", None))
        self.label_right_striker.setText(QCoreApplication.translate("main_window", u"-", None))
        self.radio_ls.setText(QCoreApplication.translate("main_window", u"Lev\u00fd \u00fato\u010dn\u00edk", None))
        self.radio_ld.setText(QCoreApplication.translate("main_window", u"Lev\u00fd obr\u00e1nce", None))
        self.label_right_defender.setText(QCoreApplication.translate("main_window", u"-", None))
        self.label_my_team.setText(QCoreApplication.translate("main_window", u"M\u016fj t\u00fdm", None))
        self.label_ld_img.setText("")
        self.label_rd_img.setText("")
        self.label_gk_img.setText("")
        self.label_ls_img.setText("")
        self.label_rs_img.setText("")
        self.label.setText(QCoreApplication.translate("main_window", u"N\u00e1zev", None))
        self.button_change_name.setText(QCoreApplication.translate("main_window", u"Zm\u011bnit", None))
        self.label_team2_name.setText(QCoreApplication.translate("main_window", u"-", None))
        self.label_16.setText(QCoreApplication.translate("main_window", u"V\u00fdsledek:", None))
        self.label_14.setText(QCoreApplication.translate("main_window", u"Soupe\u0159:", None))
        self.button_set_team2.setText(QCoreApplication.translate("main_window", u"Vytvo\u0159it soupe\u0159e", None))
        self.label_score.setText(QCoreApplication.translate("main_window", u"-", None))
        self.button_play.setText(QCoreApplication.translate("main_window", u"Hr\u00e1t", None))
        self.label_opponent_team.setText(QCoreApplication.translate("main_window", u"T\u00fdm soupe\u0159e", None))
        self.label_progress_bar.setText(QCoreApplication.translate("main_window", u"Odehr\u00e1no", None))
        self.menu_main.setTitle(QCoreApplication.translate("main_window", u"Menu", None))
    # retranslateUi       
