
from PySide6.QtCore import *  # type: ignore
from PySide6.QtGui import *  # type: ignore
from PySide6.QtWidgets import *  # type: ignore


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1101, 534)
        icon = QIcon()
        icon.addFile(u"icon.png", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.actionRestart = QAction(MainWindow)
        self.actionRestart.setObjectName(u"actionRestart")
        self.actionRestart.setIcon(icon)
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.widget = QWidget(self.centralwidget)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(30, 20, 278, 441))
        self.verticalLayout = QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.label = QLabel(self.widget)
        self.label.setObjectName(u"label")
        self.label.setMinimumSize(QSize(12, 12))
        font = QFont()
        font.setBold(True)
        self.label.setFont(font)

        self.verticalLayout.addWidget(self.label)

        self.list_players = QListWidget(self.widget)
        self.list_players.setObjectName(u"list_players")
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_players.sizePolicy().hasHeightForWidth())
        self.list_players.setSizePolicy(sizePolicy)
        self.list_players.setMinimumSize(QSize(0, 200))
        self.list_players.setBaseSize(QSize(0, 200))
        self.list_players.viewport().setProperty("cursor", QCursor(Qt.ArrowCursor))
        self.list_players.setSortingEnabled(True)

        self.verticalLayout.addWidget(self.list_players)

        self.button_add = QPushButton(self.widget)
        self.button_add.setObjectName(u"button_add")
        self.button_add.setBaseSize(QSize(7, 0))
        self.button_add.setCursor(QCursor(Qt.PointingHandCursor))

        self.verticalLayout.addWidget(self.button_add)

        self.widget_2 = QWidget(self.centralwidget)
        self.widget_2.setObjectName(u"widget_2")
        self.widget_2.setGeometry(QRect(760, 20, 291, 441))
        self.label_13 = QLabel(self.widget_2)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(11, 11, 38, 16))
        self.label_13.setFont(font)
        self.layoutWidget = QWidget(self.widget_2)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(20, 40, 242, 67))
        self.gridLayout = QGridLayout(self.layoutWidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.label_14 = QLabel(self.layoutWidget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.gridLayout.addWidget(self.label_14, 0, 0, 1, 1)

        self.label_team2_name = QLabel(self.layoutWidget)
        self.label_team2_name.setObjectName(u"label_team2_name")
        self.label_team2_name.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_team2_name, 0, 1, 1, 1)

        self.button_set_team2 = QPushButton(self.layoutWidget)
        self.button_set_team2.setObjectName(u"button_set_team2")
        self.button_set_team2.setCursor(QCursor(Qt.PointingHandCursor))

        self.gridLayout.addWidget(self.button_set_team2, 0, 2, 1, 1)

        self.label_16 = QLabel(self.layoutWidget)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.gridLayout.addWidget(self.label_16, 1, 0, 1, 1)

        self.label_score = QLabel(self.layoutWidget)
        self.label_score.setObjectName(u"label_score")
        self.label_score.setAlignment(Qt.AlignCenter)
        self.label_score.setMargin(7)

        self.gridLayout.addWidget(self.label_score, 1, 1, 1, 1)

        self.button_play = QPushButton(self.layoutWidget)
        self.button_play.setObjectName(u"button_play")
        self.button_play.setCursor(QCursor(Qt.PointingHandCursor))

        self.gridLayout.addWidget(self.button_play, 1, 2, 1, 1)

        self.widget_3 = QWidget(self.centralwidget)
        self.widget_3.setObjectName(u"widget_3")
        self.widget_3.setGeometry(QRect(330, 21, 411, 441))
        self.radio_rd = QRadioButton(self.widget_3)
        self.radio_rd.setObjectName(u"radio_rd")
        self.radio_rd.setGeometry(QRect(270, 280, 108, 20))
        self.radio_rd.setCursor(QCursor(Qt.PointingHandCursor))
        self.radio_rd.setLayoutDirection(Qt.LeftToRight)
        self.radio_gk = QRadioButton(self.widget_3)
        self.radio_gk.setObjectName(u"radio_gk")
        self.radio_gk.setGeometry(QRect(160, 410, 81, 20))
        self.radio_gk.setCursor(QCursor(Qt.PointingHandCursor))
        self.radio_gk.setLayoutDirection(Qt.LeftToRight)
        self.label_left_defender = QLabel(self.widget_3)
        self.label_left_defender.setObjectName(u"label_left_defender")
        self.label_left_defender.setGeometry(QRect(20, 260, 101, 20))
        self.label_left_defender.setAlignment(Qt.AlignCenter)
        self.label_goalkeeper = QLabel(self.widget_3)
        self.label_goalkeeper.setObjectName(u"label_goalkeeper")
        self.label_goalkeeper.setGeometry(QRect(150, 390, 101, 20))
        self.label_goalkeeper.setAlignment(Qt.AlignCenter)
        self.label_left_striker = QLabel(self.widget_3)
        self.label_left_striker.setObjectName(u"label_left_striker")
        self.label_left_striker.setGeometry(QRect(20, 130, 101, 20))
        self.label_left_striker.setAlignment(Qt.AlignCenter)
        self.radio_rs = QRadioButton(self.widget_3)
        self.radio_rs.setObjectName(u"radio_rs")
        self.radio_rs.setGeometry(QRect(270, 150, 102, 20))
        self.radio_rs.setCursor(QCursor(Qt.PointingHandCursor))
        self.radio_rs.setLayoutDirection(Qt.LeftToRight)
        self.label_right_striker = QLabel(self.widget_3)
        self.label_right_striker.setObjectName(u"label_right_striker")
        self.label_right_striker.setGeometry(QRect(270, 130, 111, 20))
        self.label_right_striker.setAlignment(Qt.AlignCenter)
        self.radio_ls = QRadioButton(self.widget_3)
        self.radio_ls.setObjectName(u"radio_ls")
        self.radio_ls.setGeometry(QRect(20, 150, 96, 20))
        self.radio_ls.setCursor(QCursor(Qt.PointingHandCursor))
        self.radio_ls.setLayoutDirection(Qt.LeftToRight)
        self.radio_ld = QRadioButton(self.widget_3)
        self.radio_ld.setObjectName(u"radio_ld")
        self.radio_ld.setGeometry(QRect(20, 280, 102, 20))
        self.radio_ld.setCursor(QCursor(Qt.PointingHandCursor))
        self.radio_ld.setLayoutDirection(Qt.LeftToRight)
        self.label_right_defender = QLabel(self.widget_3)
        self.label_right_defender.setObjectName(u"label_right_defender")
        self.label_right_defender.setGeometry(QRect(270, 260, 111, 20))
        self.label_right_defender.setAlignment(Qt.AlignCenter)
        self.label_2 = QLabel(self.widget_3)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(11, 11, 52, 16))
        self.label_2.setFont(font)
        self.label_3 = QLabel(self.widget_3)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(40, 190, 61, 61))
        sizePolicy1 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy1.setHorizontalStretch(45)
        sizePolicy1.setVerticalStretch(43)
        sizePolicy1.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy1)
        self.label_3.setBaseSize(QSize(60, 37))
        self.label_3.setPixmap(QPixmap(u"dress.png"))
        self.label_3.setScaledContents(True)
        self.label_4 = QLabel(self.widget_3)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(300, 190, 61, 61))
        sizePolicy1.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy1)
        self.label_4.setBaseSize(QSize(60, 37))
        self.label_4.setPixmap(QPixmap(u"dress.png"))
        self.label_4.setScaledContents(True)
        self.label_5 = QLabel(self.widget_3)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(170, 320, 61, 61))
        sizePolicy1.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy1)
        self.label_5.setBaseSize(QSize(60, 37))
        self.label_5.setPixmap(QPixmap(u"dress.png"))
        self.label_5.setScaledContents(True)
        self.label_6 = QLabel(self.widget_3)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(40, 50, 61, 61))
        sizePolicy1.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy1)
        self.label_6.setBaseSize(QSize(60, 37))
        self.label_6.setPixmap(QPixmap(u"dress.png"))
        self.label_6.setScaledContents(True)
        self.label_7 = QLabel(self.widget_3)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(300, 50, 61, 61))
        sizePolicy1.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy1)
        self.label_7.setBaseSize(QSize(60, 37))
        self.label_7.setPixmap(QPixmap(u"dress.png"))
        self.label_7.setScaledContents(True)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1101, 26))
        self.menuMenu = QMenu(self.menubar)
        self.menuMenu.setObjectName(u"menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuMenu.menuAction())
        self.menuMenu.addAction(self.actionRestart)
        self.menuMenu.addAction(self.actionAbout)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Football Manager by lukazko", None))
        self.actionRestart.setText(QCoreApplication.translate("MainWindow", u"Restart", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Hr\u00e1\u010di", None))
        self.button_add.setText(QCoreApplication.translate("MainWindow", u"P\u0159idat do t\u00fdmu", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Z\u00e1pas", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Soupe\u0159:", None))
        self.label_team2_name.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.button_set_team2.setText(QCoreApplication.translate("MainWindow", u"Vytvo\u0159it soupe\u0159e", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"V\u00fdsledek:", None))
        self.label_score.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.button_play.setText(QCoreApplication.translate("MainWindow", u"Hr\u00e1t", None))
        self.radio_rd.setText(QCoreApplication.translate("MainWindow", u"Prav\u00fd obr\u00e1nce", None))
        self.radio_gk.setText(QCoreApplication.translate("MainWindow", u"Brank\u00e1\u0159", None))
        self.label_left_defender.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.label_goalkeeper.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.label_left_striker.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.radio_rs.setText(QCoreApplication.translate("MainWindow", u"Prav\u00fd \u00fato\u010dn\u00edk", None))
        self.label_right_striker.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.radio_ls.setText(QCoreApplication.translate("MainWindow", u"Lev\u00fd \u00fato\u010dn\u00edk", None))
        self.radio_ld.setText(QCoreApplication.translate("MainWindow", u"Lev\u00fd obr\u00e1nce", None))
        self.label_right_defender.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"M\u016fj t\u00fdm", None))
        self.label_3.setText("")
        self.label_4.setText("")
        self.label_5.setText("")
        self.label_6.setText("")
        self.label_7.setText("")
        self.menuMenu.setTitle(QCoreApplication.translate("MainWindow", u"Menu", None))
    # retranslateUi

